SELECT NEW_TB.AUTHOR_ID,
    NEW_TB.AUTHOR_NAME,
    NEW_TB.CATEGORY,
    SUM(NEW_TB.TOTAL_SALES) AS TOTAL_SALES
FROM (
    SELECT TB2.AUTHOR_ID,
        TB2.AUTHOR_NAME,
        TB1.CATEGORY,
        TB1.PRICE * TB3.SALES AS TOTAL_SALES
    FROM BOOK TB1
        JOIN AUTHOR TB2 ON TB1.AUTHOR_ID=TB2.AUTHOR_ID
        JOIN BOOK_SALES TB3 ON TB1.BOOK_ID=TB3.BOOK_ID
    WHERE TB3.SALES_DATE >= '2022-01-01' AND TB3.SALES_DATE <= '2022-01-31'
    ORDER BY TB2.AUTHOR_ID, TB1.CATEGORY
) AS NEW_TB
GROUP BY NEW_TB.AUTHOR_ID, NEW_TB.CATEGORY
ORDER BY NEW_TB.AUTHOR_ID, NEW_TB.CATEGORY DESC;