WITH RECURSIVE RECV AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT TB1.ID, TB1.PARENT_ID, TB2.GENERATION + 1
    FROM ECOLI_DATA TB1 INNER JOIN RECV TB2 ON TB1.PARENT_ID=TB2.ID
)
SELECT ID
FROM RECV
WHERE GENERATION=3
ORDER BY ID ASC;