WITH RECURSIVE CTE
AS ( 
    SELECT ID, PARENT_ID, 1 as GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    -- Recursive 문장(읽어 올 때마다 행의 위치가 기억되어 다음번 읽어 올 때 다음 행으로 이동함)
    SELECT TB1.ID, TB1.PARENT_ID, CTE.GENERATION + 1
    FROM ECOLI_DATA as TB1 INNER JOIN CTE on TB1.PARENT_ID=CTE.ID
)
SELECT ID FROM CTE
WHERE GENERATION=3
ORDER BY ID;