# SELECT C.CAR_ID,
#     C.CAR_TYPE,
#     FLOOR(C.DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100)) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR C
#     LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
#     ON C.CAR_TYPE=D.CAR_TYPE
#         AND D.DURATION_TYPE='30일 이상'
# WHERE C.CAR_TYPE IN ('세단', 'SUV')
#     AND C.CAR_ID NOT IN (
#         SELECT CAR_ID
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#         WHERE START_DATE <= '2022-11-30'
#             AND END_DATE >= '2022-11-01'
#     )
# HAVING FEE >= 500000 AND FEE < 2000000
# ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;





SELECT TB1.CAR_ID,
    TB1.CAR_TYPE,
    FLOOR(TB1.DAILY_FEE * (
        1 - (
            CASE
                WHEN TB1.CAR_TYPE='세단' THEN (
                    SELECT DISCOUNT_RATE
                    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                    WHERE CAR_TYPE='세단'
                        AND DURATION_TYPE='30일 이상'
                )
                ELSE (
                    SELECT DISCOUNT_RATE
                    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                    WHERE CAR_TYPE='SUV'
                        AND DURATION_TYPE='30일 이상'
                )
            END
        ) / 100
    ) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR TB1
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY TB2
        ON TB1.CAR_ID=TB2.CAR_ID
WHERE TB1.CAR_TYPE IN ('세단', 'SUV')
    AND TB1.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
GROUP BY TB1.CAR_ID HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, TB1.CAR_TYPE ASC, TB1.CAR_ID DESC;