SELECT DISTINCT TB1.CAR_ID,
    TB1.CAR_TYPE,
    ROUND(TB1.DAILY_FEE * (1 - TB2.DISCOUNT_RATE / 100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS TB1
    JOIN (
        SELECT CAR_TYPE, DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE DURATION_TYPE='30일 이상'
    ) AS TB2 ON TB1.CAR_TYPE=TB2.CAR_TYPE
WHERE TB1.CAR_TYPE IN ('SUV', '세단')
    AND CAR_ID NOT IN (
        SELECT DISTINCT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
GROUP BY TB1.CAR_ID HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, TB1.CAR_TYPE ASC, TB1.CAR_ID DESC;