# WITH CTE AS
# (
#     SELECT PLAN_ID,
#         CAR_TYPE,
#         CAST(SUBSTRING(DURATION_TYPE, 1, INSTR(DURATION_TYPE, '일 이상') - 1) AS UNSIGNED) AS DURATION,
#         DISCOUNT_RATE / 100 AS DISCOUNT
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# )
# SELECT DISTINCT TB1.CAR_ID,
#     TB1.CAR_TYPE,
#     CAST(TB1.DAILY_FEE * (1 - (
#         CASE
#             WHEN TB1.CAR_TYPE='SUV' THEN (
#                 SELECT DISCOUNT
#                 FROM CTE
#                 WHERE CAR_TYPE='SUV' AND DURATION='30'
#             )
#             WHEN TB1.CAR_TYPE='세단' THEN (
#                 SELECT DISCOUNT
#                 FROM CTE
#                 WHERE CAR_TYPE='세단' AND DURATION='30'
#             )
#         END
#     )) * 30 AS UNSIGNED) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR AS TB1 LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS TB2 ON TB1.CAR_ID=TB2.CAR_ID
# WHERE NOT (TB2.START_DATE <= '2022-11-30' AND TB2.END_DATE >= '2022-11-01')
#     AND TB1.CAR_TYPE IN ('SUV', '세단')
# HAVING FEE >= 500000 AND FEE < 2000000
# ORDER BY FEE DESC, TB1.CAR_TYPE, TB1.CAR_ID DESC;

SELECT C.CAR_ID,
    C.CAR_TYPE,
    FLOOR(C.DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON C.CAR_TYPE=D.CAR_TYPE
        AND D.DURATION_TYPE='30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30'
            AND END_DATE >= '2022-11-01'
    )
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;