-- 코드를 입력하세요
SELECT FOOD_TYPE,
    REST_ID,
    REST_NAME,
    FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;

# ANOTHER SOLVE METHOD(window function)
-- SELECT REST_INFO_WITH_RANK.FOOD_TYPE,
--     REST_INFO_WITH_RANK.REST_ID,
--     REST_INFO_WITH_RANK.REST_NAME,
--     REST_INFO_WITH_RANK.FAVORITES
-- FROM (
--     SELECT FOOD_TYPE,
--         REST_ID,
--         REST_NAME,
--         FAVORITES,
--         ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RN
--     FROM REST_INFO
-- ) AS REST_INFO_WITH_RANK
-- WHERE RN=1
-- ORDER BY FOOD_TYPE DESC;