SELECT
    ID,
    CASE
        WHEN RN <= 0.25 THEN "CRITICAL"
        WHEN RN <= 0.5 THEN "HIGH"
        WHEN RN <= 0.75 THEN "MEDIUM"
        ELSE "LOW"
    END AS COLONY_NAME
FROM (
    SELECT ID,
        PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RN
    FROM ECOLI_DATA
) AS CUSTOM_TB
ORDER BY ID;