SELECT TB1.USER_ID,
    TB1.NICKNAME,
    CONCAT(TB1.CITY, ' ', CONCAT(STREET_ADDRESS1, ' ', STREET_ADDRESS2)) AS 전체주소,
    CONCAT(SUBSTRING(TB1.TLNO, 1, 3), CONCAT('-', CONCAT(SUBSTRING(TB1.TLNO, 4, 4), CONCAT('-', CONCAT(SUBSTRING(TB1.TLNO, 8, 4)))))) AS 전화번호
FROM USED_GOODS_USER AS TB1 NATURAL JOIN USED_GOODS_BOARD AS TB2
WHERE TB1.USER_ID=TB2.WRITER_ID
GROUP BY TB1.USER_ID HAVING COUNT(TB1.USER_ID) >= 3
ORDER BY TB1.USER_ID DESC;