SELECT YEAR(TB2.SALES_DATE) AS YEAR,
    MONTH(TB2.SALES_DATE) AS MONTH,
    TB1.GENDER AS GENDER,
    COUNT(DISTINCT TB2.USER_ID) AS USERS
FROM USER_INFO AS TB1 INNER JOIN ONLINE_SALE AS TB2 ON TB1.USER_ID=TB2.USER_ID
WHERE TB1.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;
