-- 코드를 입력하세요
SELECT TB2.ANIMAL_ID, TB2.NAME
FROM ANIMAL_INS AS TB1 RIGHT JOIN ANIMAL_OUTS AS TB2 ON TB1.ANIMAL_ID=TB2.ANIMAL_ID
WHERE TB1.ANIMAL_ID IS NULL;

# ANOTHER SOLVE METHOD (Subquery)
-- SELECT ANIMAL_ID, NAME
-- FROM ANIMAL_OUTS
-- WHERE ANIMAL_ID NOT IN (
--     SELECT ANIMAL_ID
--     FROM ANIMAL_INS
-- );