-- 코드를 입력하세요
SELECT YEAR(TB2.SALES_DATE) AS YEAR,
    MONTH(TB2.SALES_DATE) AS MONTH,
    COUNT(DISTINCT TB2.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT TB2.USER_ID) / (
            SELECT COUNT(DISTINCT USER_ID)
            FROM USER_INFO
            WHERE YEAR(JOINED)=2021
        ), 1) AS PUCHASED_RATIO
FROM USER_INFO AS TB1 NATURAL JOIN ONLINE_SALE AS TB2
WHERE TB1.USER_ID=TB2.USER_ID AND YEAR(TB1.JOINED)=2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH