WITH RECURSIVE CTE
AS ( 
    SELECT ID, PARENT_ID, 1 as GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT TB1.ID, TB1.PARENT_ID, CTE.GENERATION + 1
    FROM ECOLI_DATA as TB1 INNER JOIN CTE on TB1.PARENT_ID=CTE.ID
)
SELECT COUNT(DISTINCT TB1.ID) AS COUNT,
    TB1.GENERATION
FROM CTE AS TB1 LEFT JOIN CTE AS TB2 ON TB1.ID=TB2.PARENT_ID
WHERE TB2.ID IS NULL
GROUP BY TB1.GENERATION
ORDER BY TB1.GENERATION;
