SELECT HISTORY_ID,
    ROUND(TB2.DAILY_FEE * (
        1 - (
            CASE
                WHEN TB2.DIFF < 7 THEN 0
                ELSE (
                    SELECT DISCOUNT_RATE
                    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                    WHERE (CAR_TYPE, DURATION_TYPE) =
                        (TB2.CAR_TYPE, TB2.DURATION_TYPE)
                )
            END 
        ) / 100
    ) * TB2.DIFF) AS FEE
FROM (SELECT TB2.HISTORY_ID, TB2.CAR_ID, TB1.CAR_TYPE,
    DATEDIFF(END_DATE, START_DATE) + 1 AS DIFF,
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
    END AS DURATION_TYPE,
    TB1.DAILY_FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS TB2
    LEFT JOIN CAR_RENTAL_COMPANY_CAR AS TB1
        ON TB2.CAR_ID=TB1.CAR_ID
ORDER BY TB2.HISTORY_ID ASC) AS TB2
WHERE TB2.CAR_TYPE='트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;