SELECT H.HISTORY_ID,
    FLOOR(
        (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
        * C.DAILY_FEE
        * (1 - COALESCE(P.DISCOUNT_RATE, 0) / 100)
    ) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID=C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE=P.CAR_TYPE
        AND (
            CASE
                WHEN (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 90 THEN '90일 이상'
                WHEN (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 30 THEN '30일 이상'
                WHEN (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 7 THEN '7일 이상'
                ELSE 'NONE'
            END
        )=P.DURATION_TYPE
WHERE C.CAR_TYPE='트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;