WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM CTE
    WHERE HOUR < 23
)
SELECT CTE.HOUR,
    IFNULL(COUNT(TB1.ANIMAL_ID), 0) AS COUNT
FROM ANIMAL_OUTS AS TB1 RIGHT JOIN CTE ON HOUR(TB1.DATETIME)=CTE.HOUR
GROUP BY CTE.HOUR
ORDER BY CTE.HOUR;