SELECT TB1.USER_ID,
    TB1.NICKNAME,
    SUM(TB2.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER AS TB1 NATURAL JOIN USED_GOODS_BOARD AS TB2
WHERE TB1.USER_ID=TB2.WRITER_ID AND TB2.STATUS='DONE'
GROUP BY TB1.USER_ID HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;