SELECT TB1.EMP_NO,
    TB2.EMP_NAME,
    CASE
        WHEN AVG(TB1.SCORE) >= 96 THEN 'S'
        WHEN AVG(TB1.SCORE) >= 90 THEN 'A'
        WHEN AVG(TB1.SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    (TB2.SAL * (
        CASE
            WHEN AVG(TB1.SCORE) >= 96 THEN 0.2
            WHEN AVG(TB1.SCORE) >= 90 THEN 0.15
            WHEN AVG(TB1.SCORE) >= 80 THEN 0.1
            ELSE 0
        END
    )) AS BONUS
FROM HR_GRADE AS TB1 NATURAL JOIN HR_EMPLOYEES AS TB2
WHERE TB1.EMP_NO=TB2.EMP_NO
GROUP BY TB1.EMP_NO
ORDER BY TB1.EMP_NO;