SELECT TB1.ITEM_ID, TB1.ITEM_NAME, TB1.RARITY
FROM ITEM_INFO AS TB1 NATURAL JOIN ITEM_TREE AS TB2
WHERE TB2.PARENT_ITEM_ID IN (SELECT ITEM_ID
                        FROM ITEM_INFO
                        WHERE RARITY="RARE")
ORDER BY TB1.ITEM_ID DESC;