SELECT DISTINCT TB1.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS TB1
    NATURAL JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS TB2
WHERE TB1.CAR_ID=TB2.CAR_ID
    AND TB1.CAR_TYPE='세단'
    AND MONTH(TB2.START_DATE)=10
ORDER BY TB1.CAR_ID DESC;