SELECT
    ID,
    FISH_NAME,
    LENGTH
FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RN FROM FISH_INFO) AS TB1
JOIN FISH_NAME_INFO AS TB2
    ON TB1.FISH_TYPE=TB2.FISH_TYPE
WHERE RN=1
ORDER BY ID;