SELECT
    TB1.ID,
    TB2.FISH_NAME,
    TB1.LENGTH
FROM FISH_INFO AS TB1 NATURAL JOIN FISH_NAME_INFO AS TB2
WHERE TB1.FISH_TYPE=TB2.FISH_TYPE
    AND (TB2.FISH_NAME, TB1.LENGTH) IN (
        SELECT FISH_NAME, MAX(LENGTH)
        FROM FISH_INFO AS TB1 NATURAL JOIN FISH_NAME_INFO AS TB2
        WHERE TB1.FISH_TYPE=TB2.FISH_TYPE
        GROUP BY TB2.FISH_NAME
    )
ORDER BY TB1.ID;

# ANOTHER SOLVE METHOD(Window function)
-- SELECT
--     ID,
--     FISH_NAME,
--     LENGTH
-- FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RN FROM FISH_INFO) AS TB1
-- JOIN FISH_NAME_INFO AS TB2
--     ON TB1.FISH_TYPE=TB2.FISH_TYPE
-- WHERE RN=1
-- ORDER BY ID;