SELECT
    TB1.ID,
    TB2.FISH_NAME,
    TB1.LENGTH
FROM FISH_INFO AS TB1 NATURAL JOIN FISH_NAME_INFO AS TB2
WHERE TB1.FISH_TYPE=TB2.FISH_TYPE
    AND (TB2.FISH_NAME, TB1.LENGTH) IN (
        SELECT FISH_NAME, MAX(LENGTH)
        FROM FISH_INFO AS TB1 NATURAL JOIN FISH_NAME_INFO AS TB2
        WHERE TB1.FISH_TYPE=TB2.FISH_TYPE
        GROUP BY TB2.FISH_NAME
    )
ORDER BY TB1.ID;