SELECT SUM(TB2.SCORE) AS SCORE, TB1.EMP_NO, TB1.EMP_NAME, TB1.POSITION, TB1.EMAIL
FROM HR_EMPLOYEES AS TB1 NATURAL JOIN HR_GRADE AS TB2
WHERE TB2.YEAR=2022
GROUP BY TB1.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;