SELECT BOARD.TITLE, BOARD.BOARD_ID, REPL.REPLY_ID, REPL.WRITER_ID, REPL.CONTENTS, DATE_FORMAT(REPL.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_REPLY as REPL, USED_GOODS_BOARD as BOARD
WHERE REPL.BOARD_ID=BOARD.BOARD_ID AND YEAR(BOARD.CREATED_DATE)=2022 AND MONTH(BOARD.CREATED_DATE)=10
ORDER BY CREATED_DATE ASC, BOARD.TITLE ASC;