SELECT TB1.DEPT_ID, TB1.DEPT_NAME_EN, ROUND(AVG(TB2.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT AS TB1 NATURAL JOIN HR_EMPLOYEES AS TB2
WHERE TB1.DEPT_ID=TB2.DEPT_ID
GROUP BY TB1.DEPT_ID
ORDER BY AVG_SAL DESC;