SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY,
        PRODUCT_NAME,
        PRICE,
        RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANK_OF_CATEGORY
    FROM FOOD_PRODUCT
) AS NEW_TB
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    AND RANK_OF_CATEGORY=1
ORDER BY MAX_PRICE DESC;